import MID from "../../../assets/AutoClaim_icon/MID.svg";

export const PayDriverModal = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 flex justify-center items-center z-[100] p-10">
      <div className="card bg-white w-full h-full flex flex-col overflow-hidden">
        {/* Modal Header */}
        <div
          data-layer="Header"
          className="w-full px-10 py-5 bg-white shadow-[0px_4px_20px_0px_rgba(0,0,0,0.08)] inline-flex justify-between items-center relative z-10"
        >
          {/* Back Button and Title */}
          <div
            data-layer="Back Button Container"
            className="flex justify-start items-center gap-4"
          >
            <button
              onClick={onClose}
              className="hover:bg-gray-100 p-1 rounded-full transition-colors"
            >
              <img src={MID} />
            </button>
            <div
              data-layer="Header Text Container"
              className="flex justify-start items-center gap-6"
            >
              <div
                data-layer="Header Title"
                className="text-black text-2xl font-weight-600 font-['Stack_Sans_Headline'] leading-6"
              >
                Pay Driver Here
              </div>
            </div>
          </div>

          {/* Header Actions */}
          <div
            data-layer="Header Actions"
            className="flex justify-start items-center gap-5"
          >
            <button
              onClick={onClose}
              data-layer="Button"
              className="px-10 py-4 bg-blue-500 hover:bg-blue-600 active:bg-blue-700 rounded flex justify-center items-center transition-colors"
            >
              <span className="text-white text-base font-weight-400 font-['Stack_Sans_Headline'] leading-4">
                Close
              </span>
            </button>
          </div>
        </div>

        {/* The Website Content */}
        <iframe
          src="https://onlinebusiness.lloydsbank.co.uk/business/logon/login.jsp?LBGAc=T1BUT1VUTVVMVElNRVNTQUdF.MQ==.QU1DVlNfMjMwRDY0M0U1QTI1NTA5ODBBNDk1REI2JTQwQWRvYmVPcmc=.MQ==.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.QU1DVl84Rjk5MTYwRTU3MUZDMDQyN0YwMDAxMDElNDBBZG9iZU9yZw==.LTExMjQxMDY2ODB8TUNNSUR8MjM0NTY3OTExMTI0NzU3NTg5MzE5OTM0ODE5MjQ1NDg2MzU2ODF8TUNBSUR8Tk9ORXx2VmVyc2lvbnw1LjIuMA==.TEJHYzM=.eXN1c3RyeDAyMDBYNExGbGxveWRzYmFua2NvbQ==.T1BUT1VUTVVMVEk=.MDowfGMxOjF8YzM6MHxjNTowfGM0OjB8YzI6MA==.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.dHM=.bWJxY3FzbWs=&LBGAc=T1BUT1VUTVVMVElNRVNTQUdF.MQ==.QU1DVlNfMjMwRDY0M0U1QTI1NTA5ODBBNDk1REI2JTQwQWRvYmVPcmc=.MQ==.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.QU1DVl84Rjk5MTYwRTU3MUZDMDQyN0YwMDAxMDElNDBBZG9iZU9yZw==.LTExMjQxMDY2ODB8TUNNSUR8MjM0NTY3OTExMTI0NzU3NTg5MzE5OTM0ODE5MjQ1NDg2MzU2ODF8TUNBSUR8Tk9ORXx2VmVyc2lvbnw1LjIuMA==.TEJHYzM=.eXN1c3RyeDAyMDBYNExGbGxveWRzYmFua2NvbQ==.T1BUT1VUTVVMVEk=.MDowfGMxOjF8YzM6MHxjNTowfGM0OjB8YzI6MA==.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.dHM=.bWJxY3J4OGk=&LBGAc=T1BUT1VUTVVMVElNRVNTQUdF.MQ==.QU1DVlNfMjMwRDY0M0U1QTI1NTA5ODBBNDk1REI2JTQwQWRvYmVPcmc=.MQ==.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.QU1DVl84Rjk5MTYwRTU3MUZDMDQyN0YwMDAxMDElNDBBZG9iZU9yZw==.LTExMjQxMDY2ODB8TUNNSUR8MjM0NTY3OTExMTI0NzU3NTg5MzE5OTM0ODE5MjQ1NDg2MzU2ODF8TUNBSUR8Tk9ORXx2VmVyc2lvbnw1LjIuMA==.TEJHYzM=.eXN1c3RyeDAyMDBYNExGbGxveWRzYmFua2NvbQ==.T1BUT1VUTVVMVEk=.MDowfGMxOjF8YzM6MHxjNTowfGM0OjB8YzI6MA==.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.dHM=.bWJxY3M4MmQ=&LBGAc=T1BUT1VUTVVMVElNRVNTQUdF.MQ==.QU1DVlNfMjMwRDY0M0U1QTI1NTA5ODBBNDk1REI2JTQwQWRvYmVPcmc=.MQ==.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.QU1DVl84Rjk5MTYwRTU3MUZDMDQyN0YwMDAxMDElNDBBZG9iZU9yZw==.LTExMjQxMDY2ODB8TUNNSUR8MjM0NTY3OTExMTI0NzU3NTg5MzE5OTM0ODE5MjQ1NDg2MzU2ODF8TUNBSUR8Tk9ORXx2VmVyc2lvbnw1LjIuMA==.TEJHYzM=.eXN1c3RyeDAyMDBYNExGbGxveWRzYmFua2NvbQ==.T1BUT1VUTVVMVEk=.MDowfGMxOjF8YzM6MHxjNTowfGM0OjB8YzI6MA==.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.dHM=.bWJxZGR2em0=&LBGAc=T1BUT1VUTVVMVElNRVNTQUdF.MQ==.QU1DVlNfMjMwRDY0M0U1QTI1NTA5ODBBNDk1REI2JTQwQWRvYmVPcmc=.MQ==.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.QU1DVl84Rjk5MTYwRTU3MUZDMDQyN0YwMDAxMDElNDBBZG9iZU9yZw==.LTExMjQxMDY2ODB8TUNNSUR8MjM0NTY3OTExMTI0NzU3NTg5MzE5OTM0ODE5MjQ1NDg2MzU2ODF8TUNBSUR8Tk9ORXx2VmVyc2lvbnw1LjIuMA==.TEJHYzM=.eXN1c3RyeDAyMDBYNExGbGxveWRzYmFua2NvbQ==.T1BUT1VUTVVMVEk=.MDowfGMxOjF8YzM6MHxjNTowfGM0OjB8YzI6MA==.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMDY5fE1DTUlEfDgyMzE1NTA0NTUzMjUyMTA2OTQxNzUwNTE3MzQyMjk2MjgyMjYzfE1DQUFNTEgtMTczNDUxNjk1Nnw2fE1DQUFNQi0xNzM0NTE2OTU2fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTczMzkxOTM1NnN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.dHM=.bWJxZGR4aXE=&LBGAc=QU1DVlNfMjMwRDY0M0U1QTI1NTA5ODBBNDk1REI2JTQwQWRvYmVPcmc=.MQ==.T1BUT1VUTVVMVElNRVNTQUdF.MQ==.QU1DVl8yMzBENjQzRTVBMjU1MDk4MEE0OTVEQjYlNDBBZG9iZU9yZw==.LTIxMjExNzkwMzN8TUNJRFRTfDIwMzkyfE1DTUlEfDgwNTgzMjc0NTY0MzY1OTk3MDQyMTg3NjQ1MzQzNzQ5NTE5MDIwfE1DQUFNTEgtMTc2MjQ0MTUyNHw2fE1DQUFNQi0xNzYyNDQxNTI0fDZHMXluWWNMUHVpUXhZWnJzel9wa3FmTEc5eU1YQnBiMnpYNWR2SmRZUUp6UFhJbWRqMHl8TUNPUFRPVVQtMTc2MTg0MzkyNXN8Tk9ORXxNQ0FJRHxOT05FfHZWZXJzaW9ufDUuMy4w.TEJHYzM=.eXQ0eTl4MTAyMDBYNExGbGxveWRzYmFua2NvbQ==.T1BUT1VUTVVMVEk=.MDowfGMxOjF8YzM6MHxjNTowfGM0OjB8YzI6MA==.dHM=.bWhkazUyOTc=#ts:1472813081682/"
          className="w-full h-full border-none"
          title="DVLA"
        />
      </div>
    </div>
  );
};
